export const projects = [
  {
    title: "Recommendation System",
    description: "Recommends movies based on personal interest and popularity.",
    image: "/images/netflix.jpg",
    // tags: ['Java', 'XML', 'Firebase', 'Rest API'],
    // source: 'https://github.com/Coders-Of-XDA-OT/covid19-status-android',
    // visit: 'https://project.vipuljha.com/covid/',
    id: 0,
  },
  {
    title: "Personal Portfolio Website",
    description:
      "My personal website that has all my work and project experience.",
    image: "/images/portfolio.png",
    // tags: ['HTML', 'CSS', 'Bootstrap', 'JQuery'],
    // source: 'https://github.com/lordarcadius/website',
    // visit: 'https://project.vipuljha.com/website/',
    id: 1,
  },
  {
    title: "Restaurant Review Classifier",
    description: "Classifies the reviews given for a restaurant using NLP.",
    image: "/images/restaurant.jpg",
    // tags: ['Shell', 'Busybox'],
    // source: 'https://github.com/lordarcadius/ABS-Tweaks',
    // visit: 'https://forum.xda-developers.com/t/tweak-mod-arm-x86-project-dark-booster-abs-tweaks-v5-0-2-3-6-0-23-01-2016.3120404/',
    id: 2,
  },
  {
    title: "Diabetes Predictor Model",
    description: "Predicting the presence of Diabetes in a patient using ML.",
    image: "/images/diabetes.jpg",
    // tags: ['Linux', 'C', 'Makefile', 'Bash'],
    // source: 'https://github.com/lordarcadius/electrablue_mido',
    // visit: 'https://forum.xda-developers.com/t/kernel-mido-oreo-pie-electrablue-kernel-21-0-july-06-redmi-note-4.3655651/',
    id: 3,
  },
  // {
  //   title: 'Lenovo SNAPit',
  //   description: "Lenovo SNAPit Camera was one of the finest OEM camera apps back in those days. It had tonnes of unique and amazing features. I ported it to work on almost all devices at that time.",
  //   image: '/images/snapit.jpg',
  //   // tags: ['Java', 'Libs', 'Smali'],
  //   source: '#',
  //   visit: 'https://forum.xda-developers.com/t/app-port-6-0-lenovo-snapit-camera-5-8-53-for-all-devices.3608065/',
  //   id: 3,
  // },
  // {
  //   title: 'CyanogenOS Apps',
  //   description: "CyanogenOS 12.1 had a set of exclusive apps like a new theme engine and a new Truecaller integrated dialer. I ported it to work with CyanogenMod 13 and CM 13 based ROMs.",
  //   image: '/images/capps.jpg',
  //   // tags: ['Java', 'Libs'],
  //   source: '#',
  //   visit: 'https://forum.xda-developers.com/t/c-apps-v2-unofficial-6-0-x-cyanogen-os-capps-v2-for-cm13-and-cm13-based-roms.3254865/',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2017, text: "Completed my High school." },
  { year: 2018, text: "Completed my Pre-University course." },
  { year: 2019, text: "Learnt different programming languages." },
  { year: 2020, text: "Started coding and doing different projects." },
  { year: 2021, text: "Started learning ML and Web Development." },
];
